### ISSUE TITLE
analysis-net produces code that does not type

### ISSUE THREAD

**Issue by m-carrasco** [edgardozoppi/analysis-net#6] opened 2018-06-13 14:24 UTC
Hi.

I could not reproduce this issue with a synthetic code. The problem happens in StackMscorlib.System.Collections2.Stack.StackEnumerator.MoveNext

MoveNext returns a boolean value, but in the TAC a 0 is returned instead. Check label B_000A.

On the other hand IlSpy correctly decompiles the bytecode. This issue is present in advance-pta and cci-version.

DLL: https://nofile.io/f/7zdstEXZV1T/StackMscorlib.dll

Not sure if this could help, but the information in the method signature could be useful to correctly generate the TAC in this case. 

Best regards,
Manuel.

```
parameter StackEnumerator this;

  local Int32 $r1;
  local Stack $r3;
  local Int32 $r4;
  local Boolean $r5;
  local Int32 $r7;
  local Stack $r9;
  local Int32 $r10;
  local InvalidOperationException $r14;
  local Int32 $r12;
  local Int32 $r13;
  local Stack $r21;
  local Int32 $r22;
  local Int32 $r23;
  local Int32 $r24;
  local Int32 $r26;
  local Int32 $r27;
  local Boolean $r28;
  local Boolean $r29;
  local Boolean local_0;
  local Stack $r35;
  local Object[] $r36;
  local Int32 $r38;
  local Object $r39;
  local Int32 $r17;
  local Int32 $r18;
  local Int32 $r52;
  local Int32 $r42;
  local Int32 $r43;
  local Int32 local_1;
  local Int32 $r47;
  local Boolean $r48;
  local Boolean $r49;
  local Stack $r57;
  local Object[] $r58;
  local Int32 $r60;
  local Object $r61;
  local Object $r54;

  L_0000:  nop;
           $r1 = this._version;
           $r3 = this._stack;
           $r4 = $r3._version;
           $r5 = $r1 == $r4;
           Contract::Requires($r5);
           $r7 = this._version;
           $r9 = this._stack;
           $r10 = $r9._version;
           if $r7 == $r10 goto L_0031;
  B_0004:  $r14 = new InvalidOperationException;
           InvalidOperationException::.ctor($r14);
           throw $r14;
  L_0031:  nop;
           $r12 = this._index;
           $r13 = -2;
           if $r12 != $r13 goto L_0078;
  L_003B:  nop;
           $r21 = this._stack;
           $r22 = $r21._size;
           $r23 = 1;
           $r24 = $r22 - $r23;
           this._index = $r24;
           $r26 = this._index;
           $r27 = 0;
           $r28 = $r26 < $r27;
           $r29 = false;
           local_0 = $r28 == $r29;
           if local_0 == false goto L_0076;
  L_005E:  nop;
           $r35 = this._stack;
           $r36 = $r35._array;
           $r38 = this._index;
           $r39 = $r36[$r38];
           this.currentElement = $r39;
  L_0076:  nop;
           return local_0;
  L_0078:  nop;
           $r17 = this._index;
           $r18 = -1;
           if $r17 != $r18 goto L_0083;
  B_000A:  $r52 = 0;
           return $r52;
  L_0083:  nop;
           $r42 = this._index;
           $r43 = 1;
           local_1 = $r42 - $r43;
           this._index = local_1;
           $r47 = 0;
           $r48 = local_1 < $r47;
           $r49 = false;
           local_0 = $r48 == $r49;
           if local_0 == false goto L_00B8;
  L_009E:  nop;
           $r57 = this._stack;
           $r58 = $r57._array;
           $r60 = this._index;
           $r61 = $r58[$r60];
           this.currentElement = $r61;
           goto L_00BF;
  L_00B8:  nop;
           $r54 = null;
           this.currentElement = $r54;
  L_00BF:  nop;
           return local_0;

```

**Comment by edgardozoppi** [comment] 2018-06-14 07:49
Thanks a lot for reporting the bug! It should be fixed now.

I think the reason you couldn't reproduce this issue with a synthetic code is because the compiler generates different IL code in comparison with CCI, which I guess you have used to generate the dll that reproduce the error.

**Closed as completed by edgardozoppi** 2018-06-14 07:49 UTC
Labels: bug
